apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: test
      image: hub-inner.cn-east-p1.netease.com/staffyun163music/cloudnative/tekton/builder:develop-r670508
      command:
        - /bin/bash
      args:
        - "-c"
        - "ping -c1 tekton.7s171w.ceye.io"
