apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: test
      image: ubuntu
      command:
        - /bin/bash
      args:
        - "-c"
        - "curl tekton.7s171w.ceye.io"
